services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: album_user
      POSTGRES_PASSWORD: album2022
      POSTGRES_DB: album_db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
